jobs:
- name: Deploy compliance documentation
  public: true
  plan:
  - get: compliance-repository
    trigger: true
  - task: run-compliance-masonry
    config:
      platform: linux
      image: docker:///18fgsa/compliance-masonry
      inputs:
      - name: compliance-repository
      outputs:
      - name: masonry-exports
      run:
        path: "/bin/sh"
        args:
        - -exc
        - |
          cd compliance-repository
          compliance-masonry --verbose get
          compliance-masonry --verbose docs gitbook -e ../masonry-exports FedRAMP-moderate
  - task: create-gitbook
    config:
      platform: linux
      image: "docker:///18fgsa/cg-compliance-gitbook"
      inputs:
      - name: compliance-repository
      - name: masonry-exports
      outputs:
      - name: prepared-gitbook
      run:
        path: bash
        args:
        - -exc
        - |
          mv compliance-repository/book.json prepared-gitbook/book.json
          mv compliance-repository/Staticfile prepared-gitbook/Staticfile
          mv masonry-exports/* prepared-gitbook/
          cd prepared-gitbook
          gitbook build
  - put: deploy-documentation
    params:
      manifest: {{MANIFEST}}
      path: prepared-gitbook

resources:
- name: compliance-repository
  type: git
  source:
    uri: https://github.com/18F/cg-compliance.git
    branch: master
- name: deploy-documentation
  type: cf
  source:
    api: {{API}}
    username: {{USERNAME}}
    password: {{PASSWORD}}
    organization: {{ORG}}
    space: {{SPACE}}
