jobs:
- name: Deploy compliance.cloud.gov
  public: true
  plan:
  - get: compliance-repository
    trigger: true
  - task: run-compliance-masonry
    config:
      platform: linux
      image: docker:///geramirez/compliance-masonry-go#0.2
      inputs:
      - name: compliance-repository
      outputs:
      - name: masonry-exports
      run:
        path: "/bin/sh"
        args: ["-c", "cd compliance-repository && compliance-masonry-go --verbose get && compliance-masonry-go --verbose docs gitbook -e ../masonry-exports FedRAMP-med"]  
  - task: create-gitbook
    config:
      platform: linux
      image: "docker:///geramirez/gitbook-docker"
      inputs:
      - name: compliance-repository
      - name: masonry-exports
      outputs:
      - name: prepared-gitbook
      run:
        path: bash
        args: ["-c", "echo `ls masonry-exports` && mv compliance-repository/book.json prepared-gitbook/book.json && mv compliance-repository/Staticfile prepared-gitbook/Staticfile && mv masonry-exports/* prepared-gitbook/ && cd prepared-gitbook && gitbook build"]
  - put: deploy-documentation
    params:
      manifest: compliance-repository/manifest.yaml
      path: prepared-gitbook

resources:
- name: compliance-repository
  type: git
  source:
    uri: https://github.com/18F/cg-compliance.git
    branch: update2
- name: deploy-documentation
  type: cf
  source:
    api: {{API}}
    username: {{USERNAME}}
    password: {{PASSWORD}}
    organization: {{ORG}}
    space: {{SPACE}}
